settings:
  name: "There are no open ports listening"
  #example: satori run satori://devops/netstat.yml --output

install:
  - apt install net-tools -qy

netstat:
  assertStdoutNotContains: "LISTEN"
  run:
  - netstat -atupen
