settings:
  name: "There are no open ports listening"
  #example: satori run satori://devops/netstat.yml --output

install:
- apt -qy install net-tools

netstat:
  assertStdoutNotContains: "LISTEN"
  run:
  - netstat -atupen
