settings:
  name: "ESLint Security: Security rules for ESLint"
  description: "ESLint plugin that provides security-focused linting rules for JavaScript code. It helps identify potential security hotspots and dangerous patterns that could lead to vulnerabilities."
  image: node
  author:
    - https://github.com/nodesecurity
  gallery:
    - https://files.catbox.moe/v3k7b5.png
  example: satori run ./ --playbook satori://code/javascript/lint/eslint-security.yml --report --output

eslint-security:
  install:
    - npm install -g eslint @eslint/js eslint-plugin-security --silent

  test:
    assertReturnCode: 0
    assertStdout: false
    run:
      - echo "import js from '@eslint/js'; import security from 'eslint-plugin-security'; export default [js.configs.recommended, security.configs.recommended];" > /tmp/eslint-security.config.mjs
      - find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" \) | xargs -r eslint --config /tmp/eslint-security.config.mjs 2>/dev/null || true