settings:
  image: python
  name: satori web playbooks tests

install:
- pip3 install satori-ci
- satori config token ${{TOKEN}}
- satori config host https://dev-api.satori.ci

web:
  positive:
    assertReturnCode: 0
    cloudscraper:
    - satori run satori://web/cloudscraper.yml --output --data='{"URL":"http://example.com"}' --report
    cmseek:
    - satori run satori://web/cmseek.yml --data='{"URL":"http://example.com"}' --report
    cors:
      corstest:
      - satori run satori://web/cors/corstest.yml --data='{"URL":"https://satori.ci"}' --report
      corsy:
      - satori run satori://web/cors/corsy.yml --data='{"URL":"http://example.com"}' --report
    dirb:
    - satori run satori://web/dirb.yml --data='{"URL":"http://example.com"}' --report
    gauplus:
    - satori run satori://web/gauplus.yml --data='{"DOMAIN":"example.com"}' --report
    httpx:
    - satori run satori://web/httpx.yml --data='{"URL":"https://satori.ci"}' --report
    katana:
    - satori run satori://web/katana.yml --data='{"URL":"example.com"}' --report
    nikto:
    - satori run satori://web/nikto.yml --data='{"URL":"http://example.com"}' --report
    parth:
    - satori run satori://web/parth.yml --data='{"HOST":"geeksforgeeks.org"}' --report
    ppmap:
    - satori run satori://web/ppmap.yml --data='{"URL":"https://satori.ci"}' --output
    socialhunter:
    - satori run satori://web/socialhunter.yml --data='{"URL":"http://example.com"}' --output
    sqlmap:
    - satori run satori://web/sqlmap.yml --data='{"URL":"http://example.com"}' --report --output
    urldedupe:
    - satori run satori://web/urldedupe.yml --data='{"URL":"https://google.com/home?qs=value\nhttps://google.com/home?qs=secondValue"}' --output
    zgrab2:
    - satori run satori://web/zgrab2.yml --data='{"HOST":"satori.ci"}' --output
  negative:
    assertReturnCode: 1
    testssl:
    - satori run satori://web/testssl.yml --data='{"HOST":"satori.ci"}' --report --output
    sslscan:
    - satori run satori://web/sslscan.yml --data='{"HOST":"satori.ci:443"}' --report --output
